services:
    #later
    #ketflix:
    #  build: .
    #  ports:
    #    - "${APP_PORT}:3000"
    #  environment:
    #    - SMTP_KEY=${SMTP_KEY}
    #      IPTORRENTS_USER=${IPTORRENTS_USER}
    #      IPTORRENTS_PASS=${IPTORRENTS_PASS}

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/storage/media_server/config:/config:z,U
      - /mnt/storage/media_server/transcode:/transcode:z,U
      - /mnt/storage/media_server/data:/data:z,U
    environment:
      - TZ="America/New_York"
